services:
  mysql:
    image: mysql:8.0
    container_name: mysql-agendamento
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: AgendamentoDb
      MYSQL_USER: agendamento_user  
      MYSQL_PASSWORD: password
      MYSQL_ROOT_HOST: '%'  
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      timeout: 20s
      interval: 10s
      retries: 10
    command: --default-authentication-plugin=mysql_native_password --wait_timeout=28800

  api:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: agendamento-api
    ports:
      - "5110:5110"
    volumes:
      - ./backend:/src
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Server=mysql;Database=AgendamentoDb;User=root;Password=password;"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: agendamento-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - api
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
      - REACT_APP_API_URL=http://api:5110/api

volumes:
  mysql_data: