version: "3.9"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql-agendamento
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: AgendamentoDb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  api:
    build: .
    container_name: agendamento-api
    ports:
      - "5000:5000"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=AgendamentoDb;User=root;Password=password;
    command: ["dotnet", "AgendamentoMedico.API.dll"]

volumes:
  mysql_data:
